name: Generate Javadoc

on:
  push: 
    branches: ["main", "dev"]
  pull_request: 
    branches: ["main", "dev"]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v5
    - name: Set up JDK 26
      uses: actions/setup-java@v5
      with:
        java-version: '26'
        distribution: 'corretto'
        cache: maven
    - name: Generate Javadoc
      working-directory: PersonalityQuest
      run: mvn -B javadoc:javadoc
    
    - name: Publish Javadoc
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: PersonalityQuest/target/docs/javadoc/apidocs