module com.example.personalityquest {
    requires javafx.controls;
    requires javafx.fxml;
    requires java.xml;
    requires java.desktop;
    requires java.prefs;
    requires java.sql;
    requires java.net.http;
    requires bcrypt;
    requires jdk.jshell;

    opens com.example.personalityquest to javafx.fxml;
    exports com.example.personalityquest;
    exports com.example.personalityquest.Controllers.auth;
    opens com.example.personalityquest.Controllers.auth to javafx.fxml;
    exports com.example.personalityquest.Controllers.quest;
    opens com.example.personalityquest.Controllers.quest to javafx.fxml;
    exports com.example.personalityquest.Controllers.quiz;
    opens com.example.personalityquest.Controllers.quiz to javafx.fxml;
    exports com.example.personalityquest.Controllers.profile;
    opens com.example.personalityquest.Controllers.profile to javafx.fxml;
    exports com.example.personalityquest.Controllers.navigation;
    opens com.example.personalityquest.Controllers.navigation to javafx.fxml;
    exports com.example.personalityquest.Applications.auth;
    opens com.example.personalityquest.Applications.auth to javafx.fxml;
    exports com.example.personalityquest.Applications.quest;
    opens com.example.personalityquest.Applications.quest to javafx.fxml;
    exports com.example.personalityquest.Applications.quiz;
    opens com.example.personalityquest.Applications.quiz to javafx.fxml;
    exports com.example.personalityquest.Applications.profile;
    opens com.example.personalityquest.Applications.profile to javafx.fxml;
    exports com.example.personalityquest.Applications.navigation;
    opens com.example.personalityquest.Applications.navigation to javafx.fxml;
    exports com.example.personalityquest.Services.auth;
    opens com.example.personalityquest.Services.auth to javafx.fxml;
    exports com.example.personalityquest.Services.chat;
    opens com.example.personalityquest.Services.chat to javafx.fxml;
    exports com.example.personalityquest.Services.quest;
    opens com.example.personalityquest.Services.quest to javafx.fxml;
    exports com.example.personalityquest.Services.quiz;
    opens com.example.personalityquest.Services.quiz to javafx.fxml;
    exports com.example.personalityquest.Services.profile;
    opens com.example.personalityquest.Services.profile to javafx.fxml;
    exports com.example.personalityquest.Services.navigation;
    opens com.example.personalityquest.Services.navigation to javafx.fxml;
    exports com.example.personalityquest.DAO;
    opens com.example.personalityquest.DAO to javafx.fxml;
    exports com.example.personalityquest.DAO.auth;
    opens com.example.personalityquest.DAO.auth to javafx.fxml;
    exports com.example.personalityquest.DAO.chat;
    opens com.example.personalityquest.DAO.chat to javafx.fxml;
    exports com.example.personalityquest.DAO.quest;
    opens com.example.personalityquest.DAO.quest to javafx.fxml;
    exports com.example.personalityquest.DAO.profile;
    opens com.example.personalityquest.DAO.profile to javafx.fxml;
    exports com.example.personalityquest.Model.auth;
    opens com.example.personalityquest.Model.auth to javafx.fxml;
    exports com.example.personalityquest.Model.chat;
    opens com.example.personalityquest.Model.chat to javafx.fxml;
    exports com.example.personalityquest.Model.quest;
    opens com.example.personalityquest.Model.quest to javafx.fxml;
    exports com.example.personalityquest.Model.quiz;
    opens com.example.personalityquest.Model.quiz to javafx.fxml;
    exports com.example.personalityquest.Model.profile;
    opens com.example.personalityquest.Model.profile to javafx.fxml;
    exports com.example.personalityquest.Validators.auth;
    opens com.example.personalityquest.Validators.auth to javafx.fxml;
}
